version: "3"
services:
  app:
      build: .
      image: misitioba/wrapkend-worker
      container_name: wraddy-app-incubadora
      volumes:
        - ./:/app
      working_dir: /app
      env_file: ./.env
      ports:
        - 8200:8200
      command: npm run start
      restart: always
networks:
  default:
    external:
      name: webproxy